-- run Helios export script supporting drivers generated by Helios Profile Editor and Capt Zeen modules
dofile(lfs.writedir().."Scripts\\Helios\\HeliosExport14.lua")

-- you can add additional dofile statements here using the Helios Profile Editor
-- advanced DCS interface options
--
-- if you manually add any other script hooks here, use Helios Profile Editor 
-- advanced DCS interface options to let Helios know that it should not re-generate 
-- the Export.lua stub
